[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Force HTML not to be cached aggressively on signage loops
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
[build.environment]
  NODE_VERSION = "18"
